//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_LocationsWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audits
    {
        public int ID { get; set; }
        public System.DateTime Date_Changement { get; set; }
        public Nullable<bool> Change { get; set; }
        public string Ancienne_Valeur { get; set; }
        public string Nouvelle_Valeur { get; set; }
        public int ID_Location { get; set; }
    
        public virtual Locations Locations { get; set; }
    }
}
