//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_LocationsWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locations()
        {
            this.Paiement = new HashSet<Paiement>();
            this.Audits = new HashSet<Audits>();
        }
    
        public System.DateTime Date_Location { get; set; }
        public Nullable<System.DateTime> Date_Paiement { get; set; }
        public Nullable<decimal> Montant_Mensuel { get; set; }
        public Nullable<int> Nombre_Paiment { get; set; }
        public int ID_Vehicule { get; set; }
        public int ID_Client { get; set; }
        public int ID_Terme { get; set; }
        public int ID { get; set; }
        public decimal Km_Initial { get; set; }
        public Nullable<decimal> Km_Final { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Termes_Location Termes_Location { get; set; }
        public virtual Vehicules Vehicules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audits> Audits { get; set; }
    }
}
