//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_LocationsWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<int> ID_Location { get; set; }
        public string Raison_Annulation { get; set; }
    
        public virtual Locations Locations { get; set; }
    }
}
