//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_LocationsWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicules()
        {
            this.Locations = new HashSet<Locations>();
        }
    
        public int ID { get; set; }
        public string NIV { get; set; }
        public Nullable<decimal> Km { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<bool> Deja_Loue { get; set; }
        public Nullable<decimal> Valeur_Actuelle { get; set; }
        public Nullable<bool> Transmission_Automatique { get; set; }
        public Nullable<bool> Air_Climatisee { get; set; }
        public Nullable<bool> Anti_Demarreur { get; set; }
        public Nullable<int> ID_Modele { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public Nullable<int> ID_Couleur { get; set; }
    
        public virtual Couleurs Couleurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locations> Locations { get; set; }
        public virtual Modeles Modeles { get; set; }
        public virtual Types Types { get; set; }
    }
}
