//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_LocationsWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Location
    {
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Telephone { get; set; }
        public string NIV { get; set; }
        public Nullable<int> ID_Modele { get; set; }
        public Nullable<int> Annee { get; set; }
        public string Modele { get; set; }
        public Nullable<int> ID_Location { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Montant { get; set; }
    }
}
